import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
const profilePhoto = {
  borderRadius: '50%',
  border: '1px solid #fff',
}
export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome to my Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@100;400;600&family=Montserrat:wght@200;300;400&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
      </Head>
      <main>

        <div className='header'>
          <Image src='/photos/linkedin.jpeg' alt='Profile Photo Jake' style={profilePhoto} width='60' height='60' />
          <a href="www.damiclark.com">dami <b>clark</b></a>
         
          <div className="dropdown">
            <button className="dropbtn">About&thinsp;
              <i className="fa fa-caret-down"></i>
            </button>
            <div className="dropdown-content">
              <a href="#about" id='linkstyling'>About me<pre>my skills, experience and contact info</pre></a>
              <a href="#" id='linkstyling'>Projects</a>
              
            </div>
            
          </div>
          <a href="#home">DaS Ltd</a>
          <a href="#news">News</a>
        </div>

        <div className='introGrid'>
          <div className='firstImage' >

            <Image src='/photos/jake_fancy.jpg' alt="Fancy Jake" layout='fill' objectFit='cover' />
          </div>

          <div className='introductoryParagraph'>&emsp;I'm deeply passionate about the world of data, where I specialize in extracting and transforming raw numbers into actionable insights. I have a proven track record of crafting dynamic dashboards using SQL, Python, and Grafana. During my impactful tenure at Whiting Petroleum, I not only created, automated, and maintained over 300 real-time dashboards but also identified and rectified $8M in annual overcharges related to saltwater removal, contributing to a roughly ~2% annualized budget cost savings.

            <p></p>&emsp;During my tenure as a Technical Solutions Engineer at Sisense, a prominent business intelligence platform, I honed the ability to transform support calls into valuable learning experiences, placing a strong emphasis on ensuring customer satisfaction with a personalized approach. Among my notable achievements were the discovery and resolution of a significant security vulnerability, aiding customers in optimizing their analytic formulas for greater efficiency, and providing assistance in troubleshooting embedding issues.

            <p></p>&emsp;I'm committed to continual learning and enjoy every moment of the journey. If you're seeking a data enthusiast with a solid technical foundation, a penchant for automation, significant cost-saving achievements, and a positive approach, let's connect for a conversation!
            {/* <p></p>&emsp;Try the chat button in the corner of the screen to talk to me directly. */}
          </div>
        </div>
        <div className='header'>Skillset</div>
        <div className='maincomponent'><object

          data="/photos/DC_resume.pdf"
          type="application/pdf"
          width="100%"
          height="100%"
          aria-labelledby="PDF document"
        >
          <p>
            Your browser does not support PDFs.
            <a href="document.pdf">Download the PDF</a>
          </p>
        </object></div>

      </main>
    </>
  )
}
