import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className='introGrid'>
            <div className='firstImage' >
        
              <Image src='/photos/jake_fancy.jpg' alt="Fancy Jake" layout='fill' objectFit='cover' />
            </div>
            
            <div className='introductoryParagraph'>This is a paragraph</div>
        </div>
        <div>this is undeneath</div>
      </main>
    </>
  )
}
